import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    LucideProps,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    Twitter,
    User,
    X,
    UserCircle,
    Users,
    Bell,
    Key,
    Wallet,
    XCircle,
    Github,
    ShieldCheck,
    DollarSign,
    Lock,
    AlertCircle,
    UserPlus,
    ScrollText,
    FlaskConical,
    Loader,
    School2,
    Shapes,
    BookOpen,
    Upload,
    UploadCloud,
    Search,
    Contact,
    Box,
    Archive,
    Pencil,
    FileUp,
    CircleDollarSign,
    BookMarked,
    AlignJustify,
    type LucideIcon, CircleOff,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
    logo: Command,
    menu: AlignJustify,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    userCircle: UserCircle,
    users: Users,
    bell: Bell,
    key: Key,
    wallet: Wallet,
    xCircle: XCircle,
    circleOff: CircleOff,
    gitHub: Github,
    twitter: Twitter,
    check: Check,
    shieldCheck: ShieldCheck,
    dollarSign: DollarSign,
    lock: Lock,
    alertCircle: AlertCircle,
    userPlus: UserPlus,
    scrollText: ScrollText,
    flaskConical: FlaskConical,
    loader: Loader,
    school: School2,
    shapes: Shapes,
    bookOpen: BookOpen,
    upload: Upload,
    uploadCloud: UploadCloud,
    search: Search,
    contact: Contact,
    box: Box,
    archive: Archive,
    pencil: Pencil,
    fileUp: FileUp,
    circleDollarSign: CircleDollarSign,
    bookMarked: BookMarked,
}
